/**
 * The Verifier Economy, end to end on devnet — one command, no Docker, no LLM key required.
 *
 *   Round 1  the cheapest bid wins … and it's slop. The paid verifier re-derives the order binding,
 *            runs the buyer's acceptance spec, REJECTS with a reproducible failure list, and after
 *            the escrow deadline refunds the payer on-chain. The verifier still earns its fee.
 *   Round 2  the buyer now filters on verdict history (reputation is just public VERDICTs), the
 *            honest seller wins, the delivery passes, and the verifier releases: seller paid,
 *            verifier paid, every step a devnet Explorer link.
 *
 * Wallets come from the kit's `.env` (node scripts/setup.js): the buyer funds orders, the kit's
 * arbiter keypair serves as the verifier (same neutral-party slot, now per-order and paid), and
 * extra seller personas are generated once and appended to `.env`.
 */
import { appendFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram, Transaction, sendAndConfirmTransaction } from '@solana/web3.js'
import bs58 from 'bs58'
import { MarketBus } from './bus.js'
import { runSeller, type SellerPersona } from './agents/seller.js'
import { runVerifier } from './agents/verifier.js'
import { runRound, type BuyerConfig } from './agents/buyer.js'
import { parseVerdict } from './protocol.js'
import { INVOICE_SPEC, JOBS } from './data.js'
import { explorer } from './chain.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..')
const ENV_PATH = path.join(ROOT, '.env')
if (existsSync(ENV_PATH)) process.loadEnvFile(ENV_PATH)

const RPC = process.env.SOLANA_RPC_URL ?? 'https://api.devnet.solana.com'
const SSE_PORT = Number(process.env.VERIFIER_ECONOMY_PORT ?? 3031)

const keypairFromEnv = (name: string): Keypair | undefined => {
  const b58 = process.env[name]
  return b58 ? Keypair.fromSecretKey(bs58.decode(b58)) : undefined
}

/** Personas beyond the kit's two wallets are generated once and appended to .env (devnet-only keys). */
const ensureKeypair = (name: string): Keypair => {
  const existing = keypairFromEnv(name)
  if (existing) return existing
  const kp = Keypair.generate()
  appendFileSync(ENV_PATH, `\n# ${name} — generated by examples/verifier-economy (devnet persona)\n${name}=${bs58.encode(kp.secretKey)}\n`)
  process.env[name] = bs58.encode(kp.secretKey)
  return kp
}

async function main(): Promise<void> {
  const payer = keypairFromEnv('BUYER_KEYPAIR_B58')
  const verifierWallet = keypairFromEnv('ARBITER_KEYPAIR_B58')
  const honestWallet = keypairFromEnv('SELLER_KEYPAIR_B58')
  if (!payer || !verifierWallet || !honestWallet)
    throw new Error('missing wallets — run `node scripts/setup.js` at the repo root first (then fund the buyer at faucet.solana.com)')
  const slopWallet = ensureKeypair('SELLER_SLOP_KEYPAIR_B58')
  const noshowWallet = ensureKeypair('SELLER_NOSHOW_KEYPAIR_B58')

  const connection = new Connection(RPC, 'confirmed')
  const payerBal = await connection.getBalance(payer.publicKey)
  if (payerBal < 0.1 * LAMPORTS_PER_SOL)
    throw new Error(`buyer ${payer.publicKey.toBase58()} has ${payerBal / LAMPORTS_PER_SOL} SOL — fund it at https://faucet.solana.com`)

  // The verifier signs its own verdicts, so it needs tx-fee dust — topped up from the payer, same
  // as the kit's proxy does for its arbiter.
  if ((await connection.getBalance(verifierWallet.publicKey)) < 0.01 * LAMPORTS_PER_SOL) {
    const tx = new Transaction().add(SystemProgram.transfer({
      fromPubkey: payer.publicKey, toPubkey: verifierWallet.publicKey, lamports: Math.round(0.02 * LAMPORTS_PER_SOL),
    }))
    await sendAndConfirmTransaction(connection, tx, [payer])
  }

  const bus = new MarketBus()
  bus.serve(SSE_PORT)

  const personas: SellerPersona[] = [
    { name: 'atlas-extracts', wallet: honestWallet, conduct: 'honest', floorSol: 0.006 },
    { name: 'quickparse-99', wallet: slopWallet, conduct: 'slop', floorSol: 0.004 },
    { name: 'ghostworks', wallet: noshowWallet, conduct: 'noshow', floorSol: 0.009 },
  ]
  const sellerWalletOf = (name: string): PublicKey | undefined =>
    personas.find((p) => p.name === name)?.wallet.publicKey
  for (const p of personas) runSeller(bus, p)
  runVerifier(bus, { name: 'veritas', wallet: verifierWallet, rpcUrl: RPC })

  // Reputation = the public verdict trail. The buyer refuses sellers with a REJECTED history.
  const rejectedSellers = new Set<string>()
  const winnersByReference = new Map<string, string>()
  bus.onMessage(({ text }) => {
    const v = parseVerdict(text)
    if (v?.result === 'REJECTED') {
      const seller = winnersByReference.get(v.reference)
      if (seller) rejectedSellers.add(seller)
    }
  })

  const wallets = {
    payer: payer.publicKey, 'atlas-extracts': honestWallet.publicKey,
    'quickparse-99': slopWallet.publicKey, veritas: verifierWallet.publicKey,
  }
  const postBalances = async (): Promise<void> => {
    const parts = await Promise.all(Object.entries(wallets).map(async ([label, pk]) =>
      `${label}=${((await connection.getBalance(pk)) / LAMPORTS_PER_SOL).toFixed(6)}`))
    bus.post('chain', `BALANCES ${parts.join(' ')}`)
  }
  const balancesTimer = setInterval(() => { void postBalances() }, 4000)

  const cfg: BuyerConfig = {
    name: 'procura', wallet: payer, rpcUrl: RPC,
    verifier: verifierWallet.publicKey,
    feeSol: 0.002, budgetSol: 0.02,
    deadlineSecs: 45, graceSecs: 600, bidWindowMs: 2500,
  }

  await postBalances()
  for (let round = 1; round <= 2; round++) {
    bus.post('demo', `ROUND ${round} — ${round === 1 ? 'price competition, no reputation yet' : `reputation active (excluded: ${[...rejectedSellers].join(', ') || 'none'})`}`)
    const result = await runRound(
      bus, cfg, round, JOBS[0].docId, INVOICE_SPEC,
      (name) => (rejectedSellers.has(name) ? undefined : sellerWalletOf(name)),
    )
    if (!result) continue
    winnersByReference.set(result.reference, result.winner.by)
    // Wait for the settled verdict (the one carrying the tx signature).
    const settled = await bus.waitFor(
      ({ text }) => { const v = parseVerdict(text); return v && v.reference === result.reference && v.sig ? v : null },
      (cfg.deadlineSecs + 60) * 1000,
    )
    if (!settled) throw new Error(`round ${round}: no settlement within the window`)
    console.log(`\nround ${round}: ${settled.result} — ${explorer('tx', settled.sig!)}\n`)
  }

  await postBalances()
  clearInterval(balancesTimer)
  bus.post('demo', 'DONE — every verdict above settles on devnet; follow the Explorer links.')
  setTimeout(() => process.exit(0), 3000) // let the dashboard drain the SSE buffer
}

main().catch((e) => { console.error(e); process.exit(1) })
